/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-25 08:17:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/comm/plugIn.jsp", Long.valueOf(1698197551576L));
    _jspx_dependants.put("/WEB-INF/views/comm/footer.jsp", Long.valueOf(1698119682502L));
    _jspx_dependants.put("/WEB-INF/views/comm/header.jsp", Long.valueOf(1698219913055L));
    _jspx_dependants.put("/WEB-INF/views/comm/plugIn2.jsp", Long.valueOf(1698192771691L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("    <meta name=\"generator\" content=\"Hugo 0.101.0\">\r\n");
      out.write("    <title>Pricing example · Bootstrap v4.6</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\" integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://getbootstrap.com/docs/4.6/examples/pricing/pricing.css\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicons -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      .bd-placeholder-img {\r\n");
      out.write("        font-size: 1.125rem;\r\n");
      out.write("        text-anchor: middle;\r\n");
      out.write("        -webkit-user-select: none;\r\n");
      out.write("        -moz-user-select: none;\r\n");
      out.write("        -ms-user-select: none;\r\n");
      out.write("        user-select: none;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      @media (min-width: 768px) {\r\n");
      out.write("        .bd-placeholder-img-lg {\r\n");
      out.write("          font-size: 3.5rem;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<div class=\"d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm\">\r\n");
      out.write("  <h5 class=\"my-0 mr-md-auto font-weight-normal\"><a href=\"/\">DocMall</a></h5>\r\n");
      out.write("  <nav class=\"my-2 my-md-0 mr-md-3\">\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"#\">Login</a>\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"/member/join\">Join</a>\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"#\">MyrPage</a>\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"#\">Order</a>\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"#\">Cart</a>\r\n");
      out.write("  </nav>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center\">\r\n");
      out.write("  <h1 class=\"display-4\">Pricing</h1>\r\n");
      out.write("  <p class=\"lead\">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"card-deck mb-3 text-center\">\r\n");
      out.write("    <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("      <div class=\"card-header\">\r\n");
      out.write("        <h4 class=\"my-0 font-weight-normal\">Free</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h1 class=\"card-title pricing-card-title\">$0 <small class=\"text-muted\">/ mo</small></h1>\r\n");
      out.write("        <ul class=\"list-unstyled mt-3 mb-4\">\r\n");
      out.write("          <li>10 users included</li>\r\n");
      out.write("          <li>2 GB of storage</li>\r\n");
      out.write("          <li>Email support</li>\r\n");
      out.write("          <li>Help center access</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-block btn-outline-primary\">Sign up for free</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("      <div class=\"card-header\">\r\n");
      out.write("        <h4 class=\"my-0 font-weight-normal\">Pro</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h1 class=\"card-title pricing-card-title\">$15 <small class=\"text-muted\">/ mo</small></h1>\r\n");
      out.write("        <ul class=\"list-unstyled mt-3 mb-4\">\r\n");
      out.write("          <li>20 users included</li>\r\n");
      out.write("          <li>10 GB of storage</li>\r\n");
      out.write("          <li>Priority email support</li>\r\n");
      out.write("          <li>Help center access</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-block btn-primary\">Get started</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card mb-4 shadow-sm\">\r\n");
      out.write("      <div class=\"card-header\">\r\n");
      out.write("        <h4 class=\"my-0 font-weight-normal\">Enterprise</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h1 class=\"card-title pricing-card-title\">$29 <small class=\"text-muted\">/ mo</small></h1>\r\n");
      out.write("        <ul class=\"list-unstyled mt-3 mb-4\">\r\n");
      out.write("          <li>30 users included</li>\r\n");
      out.write("          <li>15 GB of storage</li>\r\n");
      out.write("          <li>Phone and email support</li>\r\n");
      out.write("          <li>Help center access</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-block btn-primary\">Contact us</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("      <div class=\"col-12 col-md\">\r\n");
      out.write("        <img class=\"mb-2\" src=\"/docs/4.6/assets/brand/bootstrap-solid.svg\" alt=\"\" width=\"24\" height=\"24\">\r\n");
      out.write("        <small class=\"d-block mb-3 text-muted\">© 2017-2022</small>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-6 col-md\">\r\n");
      out.write("        <h5>Features</h5>\r\n");
      out.write("        <ul class=\"list-unstyled text-small\">\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Cool stuff</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Random feature</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Team feature</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Stuff for developers</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Another one</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Last time</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-6 col-md\">\r\n");
      out.write("        <h5>Resources</h5>\r\n");
      out.write("        <ul class=\"list-unstyled text-small\">\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Resource</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Resource name</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Another resource</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Final resource</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-6 col-md\">\r\n");
      out.write("        <h5>About</h5>\r\n");
      out.write("        <ul class=\"list-unstyled text-small\">\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Team</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Locations</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Privacy</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Terms</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js\" integrity=\"sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+\" crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
