/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-10-26 02:04:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/comm/plugIn.jsp", Long.valueOf(1698197551576L));
    _jspx_dependants.put("/WEB-INF/views/comm/footer.jsp", Long.valueOf(1698119682502L));
    _jspx_dependants.put("/WEB-INF/views/comm/header.jsp", Long.valueOf(1698219913055L));
    _jspx_dependants.put("/WEB-INF/views/comm/plugIn2.jsp", Long.valueOf(1698192771691L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("  <meta name=\"generator\" content=\"Hugo 0.101.0\">\r\n");
      out.write("  <title>Pricing example · Bootstrap v4.6</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap core CSS -->\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\" integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://getbootstrap.com/docs/4.6/examples/pricing/pricing.css\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicons -->\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      .bd-placeholder-img {\r\n");
      out.write("        font-size: 1.125rem;\r\n");
      out.write("        text-anchor: middle;\r\n");
      out.write("        -webkit-user-select: none;\r\n");
      out.write("        -moz-user-select: none;\r\n");
      out.write("        -ms-user-select: none;\r\n");
      out.write("        user-select: none;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      @media (min-width: 768px) {\r\n");
      out.write("        .bd-placeholder-img-lg {\r\n");
      out.write("          font-size: 3.5rem;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<div class=\"d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm\">\r\n");
      out.write("  <h5 class=\"my-0 mr-md-auto font-weight-normal\"><a href=\"/\">DocMall</a></h5>\r\n");
      out.write("  <nav class=\"my-2 my-md-0 mr-md-3\">\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"#\">Login</a>\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"/member/join\">Join</a>\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"#\">MyrPage</a>\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"#\">Order</a>\r\n");
      out.write("    <a class=\"p-2 text-dark\" href=\"#\">Cart</a>\r\n");
      out.write("  </nav>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"text-center\">\r\n");
      out.write("        <div class=\"box box-primary\">\r\n");
      out.write("          <div class=\"box-header with-border\">\r\n");
      out.write("            <h3 class=\"box-title\">회원가입</h3>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <form role=\"form\" id=\"jinForm\" method=\"post\" action=\"\">\r\n");
      out.write("            <div class=\"box-body\">\r\n");
      out.write("              <div class=\"form-group row\">\r\n");
      out.write("                <label for=\"mbsp_id\" class=\"col-2\">아이디</label>\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"mbsp_id\" id=\"mbsp_id\" placeholder=\"아이디 입력....\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-2\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-outline-info\" id=\"idCheck\">IDCheck</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group row\">\r\n");
      out.write("                <label for=\"mbsp_password\" class=\"col-2\">비밀번호</label>\r\n");
      out.write("                <div class=\"col-10\">\r\n");
      out.write("                  <input type=\"password\" class=\"form-control\" name=\"mbsp_password\" id=\"mbsp_password\"\r\n");
      out.write("                    placeholder=\"비밀번호 입력....\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group row\">\r\n");
      out.write("                <label for=\"mbsp_password2\" class=\"col-2\">비밀번호 확인</label>\r\n");
      out.write("                <div class=\"col-10\">\r\n");
      out.write("                  <input type=\"password\" class=\"form-control\" id=\"mbsp_password2\" placeholder=\"비밀번호 확인....\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group row\">\r\n");
      out.write("                <label for=\"mbsp_name\" class=\"col-2\">이름</label>\r\n");
      out.write("                <div class=\"col-10\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"mbsp_name\" id=\"mbsp_name\" placeholder=\"이름입력....\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group row\">\r\n");
      out.write("                <label for=\"mbsp_email\" class=\"col-2\">전자우편</label>\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <input type=\"email\" class=\"form-control\" name=\"mbsp_email\" id=\"mbsp_email\" placeholder=\"전자우편입력....\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-2\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-outline-info\" id=\"mailAuth\">메일인증</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group row\">\r\n");
      out.write("                <label for=\"mbsp_id\" class=\"col-2\">인증</label>\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"authCode\" id=\"authCode\" placeholder=\"메일인증코드 입력....\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-2\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-outline-info\" id=\"btnConfirmAuth\">인증확인</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group row\">\r\n");
      out.write("                <label for=\"sample2_postcode\" class=\"col-2\">우편번호</label>\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"mbsp_zipcode\" id=\"sample2_postcode\"\r\n");
      out.write("                    placeholder=\"우편번호 입력....\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-2\">\r\n");
      out.write("                  <button type=\"button\" onclick=\"sample2_execDaumPostcode()\" class=\"btn btn-outline-info\">우편번호\r\n");
      out.write("                    찾기</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group row\">\r\n");
      out.write("                <label for=\"sample2_address\" class=\"col-2\">기본주소</label>\r\n");
      out.write("                <div class=\"col-10\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"mbsp_addr\" id=\"sample2_address\"\r\n");
      out.write("                    placeholder=\"기본주소 입력.....\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group row\">\r\n");
      out.write("                <label for=\"sample2_detailAddress\" class=\"col-2\">상세주소</label>\r\n");
      out.write("                <div class=\"col-10\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"mbsp_deaddr\" id=\"sample2_detailAddress\"\r\n");
      out.write("                    placeholder=\"상세주소 입력...\">\r\n");
      out.write("                  <input type=\"hidden\" id=\"sample2_extraAddress\" placeholder=\"참고항목\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group row\">\r\n");
      out.write("                <label for=\"mbsp_phone\" class=\"col-2\">전화번호</label>\r\n");
      out.write("                <div class=\"col-10\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" name=\"mbsp_phone\" id=\"mbsp_phone\" placeholder=\"전화번호 입력....\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"box-footer\">\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-primary\" id=\"btnJoin\">회원가입</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("      <div class=\"col-12 col-md\">\r\n");
      out.write("        <img class=\"mb-2\" src=\"/docs/4.6/assets/brand/bootstrap-solid.svg\" alt=\"\" width=\"24\" height=\"24\">\r\n");
      out.write("        <small class=\"d-block mb-3 text-muted\">© 2017-2022</small>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-6 col-md\">\r\n");
      out.write("        <h5>Features</h5>\r\n");
      out.write("        <ul class=\"list-unstyled text-small\">\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Cool stuff</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Random feature</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Team feature</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Stuff for developers</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Another one</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Last time</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-6 col-md\">\r\n");
      out.write("        <h5>Resources</h5>\r\n");
      out.write("        <ul class=\"list-unstyled text-small\">\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Resource</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Resource name</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Another resource</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Final resource</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-6 col-md\">\r\n");
      out.write("        <h5>About</h5>\r\n");
      out.write("        <ul class=\"list-unstyled text-small\">\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Team</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Locations</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Privacy</a></li>\r\n");
      out.write("          <li><a class=\"text-muted\" href=\"#\">Terms</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- iOS에서는 position:fixed 버그가 있음, 적용하는 사이트에 맞게 position:absolute 등을 이용하여 top,left값 조정 필요 -->\r\n");
      out.write("      <div id=\"layer\" style=\"display:none;position:fixed;overflow:hidden;z-index:1;-webkit-overflow-scrolling:touch;\">\r\n");
      out.write("        <img src=\"//t1.daumcdn.net/postcode/resource/images/close.png\" id=\"btnCloseLayer\"\r\n");
      out.write("          style=\"cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1\" onclick=\"closeDaumPostcode()\"\r\n");
      out.write("          alt=\"닫기 버튼\">\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("      <script>\r\n");
      out.write("        // 우편번호 찾기 화면을 넣을 element\r\n");
      out.write("        var element_layer = document.getElementById('layer');\r\n");
      out.write("\r\n");
      out.write("        function closeDaumPostcode() {\r\n");
      out.write("          // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("          element_layer.style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function sample2_execDaumPostcode() {\r\n");
      out.write("          new daum.Postcode({\r\n");
      out.write("            oncomplete: function (data) {\r\n");
      out.write("              // 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("              // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("              // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("              var addr = ''; // 주소 변수\r\n");
      out.write("              var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("              //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("              if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                addr = data.roadAddress;\r\n");
      out.write("              } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                addr = data.jibunAddress;\r\n");
      out.write("              }\r\n");
      out.write("\r\n");
      out.write("              // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("              if (data.userSelectedType === 'R') {\r\n");
      out.write("                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                if (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("                  extraAddr += data.bname;\r\n");
      out.write("                }\r\n");
      out.write("                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                if (data.buildingName !== '' && data.apartment === 'Y') {\r\n");
      out.write("                  extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                }\r\n");
      out.write("                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                if (extraAddr !== '') {\r\n");
      out.write("                  extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                }\r\n");
      out.write("                // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById(\"sample2_extraAddress\").value = extraAddr;\r\n");
      out.write("\r\n");
      out.write("              } else {\r\n");
      out.write("                document.getElementById(\"sample2_extraAddress\").value = '';\r\n");
      out.write("              }\r\n");
      out.write("\r\n");
      out.write("              // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("              document.getElementById('sample2_postcode').value = data.zonecode;\r\n");
      out.write("              document.getElementById(\"sample2_address\").value = addr;\r\n");
      out.write("              // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("              document.getElementById(\"sample2_detailAddress\").focus();\r\n");
      out.write("\r\n");
      out.write("              // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("              // (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)\r\n");
      out.write("              element_layer.style.display = 'none';\r\n");
      out.write("            },\r\n");
      out.write("            width: '100%',\r\n");
      out.write("            height: '100%',\r\n");
      out.write("            maxSuggestItems: 5\r\n");
      out.write("          }).embed(element_layer);\r\n");
      out.write("\r\n");
      out.write("          // iframe을 넣은 element를 보이게 한다.\r\n");
      out.write("          element_layer.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("          // iframe을 넣은 element의 위치를 화면의 가운데로 이동시킨다.\r\n");
      out.write("          initLayerPosition();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 브라우저의 크기 변경에 따라 레이어를 가운데로 이동시키고자 하실때에는\r\n");
      out.write("        // resize이벤트나, orientationchange이벤트를 이용하여 값이 변경될때마다 아래 함수를 실행 시켜 주시거나,\r\n");
      out.write("        // 직접 element_layer의 top,left값을 수정해 주시면 됩니다.\r\n");
      out.write("        function initLayerPosition() {\r\n");
      out.write("          var width = 300; //우편번호서비스가 들어갈 element의 width\r\n");
      out.write("          var height = 400; //우편번호서비스가 들어갈 element의 height\r\n");
      out.write("          var borderWidth = 5; //샘플에서 사용하는 border의 두께\r\n");
      out.write("\r\n");
      out.write("          // 위에서 선언한 값들을 실제 element에 넣는다.\r\n");
      out.write("          element_layer.style.width = width + 'px';\r\n");
      out.write("          element_layer.style.height = height + 'px';\r\n");
      out.write("          element_layer.style.border = borderWidth + 'px solid';\r\n");
      out.write("          // 실행되는 순간의 화면 너비와 높이 값을 가져와서 중앙에 뜰 수 있도록 위치를 계산한다.\r\n");
      out.write("          element_layer.style.left = (((window.innerWidth || document.documentElement.clientWidth) - width) / 2 - borderWidth) + 'px';\r\n");
      out.write("          element_layer.style.top = (((window.innerHeight || document.documentElement.clientHeight) - height) / 2 - borderWidth) + 'px';\r\n");
      out.write("        }\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js\" integrity=\"sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+\" crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("          // jquery.slim.min.js 파일에 jQuery 명령어가 정의되어 있음\r\n");
      out.write("          // $(): JQuery() 함수 사용 별칭\r\n");
      out.write("          // ready(): 브라우저가 html 태그를 모두 읽고난 후에 동작하는 이벤트 메서드\r\n");
      out.write("          // JS 이벤트 등록: https://www.w3schools.com/js/js_htmldom_eventlistener.asp \r\n");
      out.write("          $(document).ready(function () {\r\n");
      out.write("            let useIDCheck = false; //아이디 중복체크 사용유무 확인\r\n");
      out.write("            // JS 문법: document.getElementById(\"idCheck\");\r\n");
      out.write("            $(\"#idCheck\").click(function () {\r\n");
      out.write("              //   alert(\"아이디 중복 체크\");\r\n");
      out.write("              if ($(\"#mbsp_id\").val() == \"\") {\r\n");
      out.write("                alert(\"아이디를 입력하세요.\");\r\n");
      out.write("                $(\"#mbsp_id\").focus();\r\n");
      out.write("                return;\r\n");
      out.write("              }\r\n");
      out.write("              // 아이디 중복 체크\r\n");
      out.write("              $.ajax({\r\n");
      out.write("                url: '/member/idCheck',\r\n");
      out.write("                type: 'get',\r\n");
      out.write("                dataType: 'text',\r\n");
      out.write("                data: { mbsp_id: $(\"#mbsp_id\").val() },\r\n");
      out.write("                success: function (result) {\r\n");
      out.write("                  if (result == \"yes\") {\r\n");
      out.write("                    alert(\"아이디 사용가능\");\r\n");
      out.write("                    useIDCheck = \"true\";\r\n");
      out.write("                  } else {\r\n");
      out.write("                    alert(\"아이디 사용불가능\");\r\n");
      out.write("                    useIDCheck = \"false\";\r\n");
      out.write("                    $(\"#mbsp_id\").val(\"\"); //아이디 텍스트박스를 값을 즈음\r\n");
      out.write("                    $(\"#mbsp_id\").focus(); //포커스\r\n");
      out.write("                  }\r\n");
      out.write("                }\r\n");
      out.write("              });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // 메일 인증 요청\r\n");
      out.write("            $(\"#mailAuth\").click(function () {\r\n");
      out.write("              if ($(\"#mbsp_email\").val() == \"\") {\r\n");
      out.write("                alert(\"이메일을 입력하세요\");\r\n");
      out.write("                $(\"#mbsp_email\").focus();\r\n");
      out.write("                return;\r\n");
      out.write("              }\r\n");
      out.write("\r\n");
      out.write("              $.ajax({\r\n");
      out.write("                url: '/email/authcode',\r\n");
      out.write("                type: 'get',\r\n");
      out.write("                dataType: 'text', // 스프링에서 보내는 데이터의 타입: <String> -> \"success\" -> text\r\n");
      out.write("                data: { receiverMail: $(\"#mbsp_email\").val() }, // EmailDTO ─ private String receiverMail;\r\n");
      out.write("                success: function (result) {\r\n");
      out.write("                  if (result == \"success\") {\r\n");
      out.write("                    alert(\"인증 메일이 발송되었습니다. 메일 확인 바랍니다.\")\r\n");
      out.write("                  }\r\n");
      out.write("                }\r\n");
      out.write("              });\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            //인증확인\r\n");
      out.write("            $(\"#btnConfirmAuth\").click(function() {\r\n");
      out.write("\r\n");
      out.write("              if($(\"#authCode\").val() == \"\") {\r\n");
      out.write("                alert(\"인증코드를 입력하세요.\");\r\n");
      out.write("                $(\"#authCode\").focus();\r\n");
      out.write("                return;\r\n");
      out.write("              }\r\n");
      out.write("\r\n");
      out.write("              let isConFirmAuth = false; //메일 인증을 다시해주세요\r\n");
      out.write("\r\n");
      out.write("              //인증확인 요청 \r\n");
      out.write("              $.ajax({\r\n");
      out.write("                url: '/email/confirmAuthcode',\r\n");
      out.write("                type:'get' ,\r\n");
      out.write("                dataType: 'text',\r\n");
      out.write("                data: {authcode : $(\"#authCode\").val()},\r\n");
      out.write("                success: function(result) {\r\n");
      out.write("                  if(result == \"success\") {\r\n");
      out.write("                    alert(\"인증성공\");\r\n");
      out.write("                    isConFirmAuth = true;\r\n");
      out.write("                  } else if(result == \"fail\") {\r\n");
      out.write("                    alert(\"인증코드가 틀립니다. 확인바랍니다.\");\r\n");
      out.write("                    $(\"#authcode\").val(\"\");\r\n");
      out.write("                    isConFirmAuth = false;\r\n");
      out.write("                  }else if(result == \"request\")\r\n");
      out.write("                  alert(\"메일인증 요청을 다시 해주세요.\");\r\n");
      out.write("                  $(\"#authcode\").val(\"\");\r\n");
      out.write("                  isConFirmAuth = false;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("              });\r\n");
      out.write("\r\n");
      out.write("              });\r\n");
      out.write("\r\n");
      out.write("              //form 태그 참조 <form role=\"form\" id=\"jinForm\" method=\"post\" action=\"\">\r\n");
      out.write("\r\n");
      out.write("              let joinForm = $(\"joinForm\");\r\n");
      out.write("\r\n");
      out.write("              //회원가입 버튼\r\n");
      out.write("              $(\"#btnJoin\").click(function() {\r\n");
      out.write("\r\n");
      out.write("                //회원가입 유효성 검사\r\n");
      out.write("\r\n");
      out.write("                if(!useIDCheck) {\r\n");
      out.write("                alert(\"아이디 중복체크 바랍니다.\");\r\n");
      out.write("                return;\r\n");
      out.write("              }\r\n");
      out.write("              \r\n");
      out.write("\r\n");
      out.write("              if(!isConFirmAuth) {\r\n");
      out.write("                alert(\"메일 인증 확인 바랍니다.\");\r\n");
      out.write("                return;\r\n");
      out.write("              }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              //폼 전송작업\r\n");
      out.write("\r\n");
      out.write("              joinForm.submit();  \r\n");
      out.write("              });\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("          });\r\n");
      out.write("        </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
